language: go

go:
  - 1.9

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci